### ISSUE TITLE
💫 [FeatureRequest] - Read Models from Different Directories

### ISSUE THREAD

**Issue by ialhabbal** [Dartvauder/NeuroSandboxWebUI#349]
### Feature request

Read models available locally in different directories on user's PC (all models, loras, embeddings).

### Motivation

Right now it is impractical to redownload all the models that a user will have on his hard drive again. I already have over 450gb of models and loras under ComfyUI and they are organized into sub directories (SD1.5, SDXL, SD3.5, Flux). I am unable to point this program to read them, and I cannot make another copy specifically for this program.

### Your contribution

My suggestion.

**Comment by Dartvauder** [comment]
> ### Feature request
> Read models available locally in different directories on user's PC (all models, loras, embeddings).
> 
> ### Motivation
> Right now it is impractical to redownload all the models that a user will have on his hard drive again. I already have over 450gb of models and loras under ComfyUI and they are organized into sub directories (SD1.5, SDXL, SD3.5, Flux). I am unable to point this program to read them, and I cannot make another copy specifically for this program.
> 
> ### Your contribution
> My suggestion.

Hi friend. To be honest, I don't know yet how to implement this correctly so that there are no conflicts and errors. I will have to change a lot of things radically. Unfortunately, this is not planned for now, in the future I will try to return to this issue and do something about it. In the meantime, there are two options to choose from: transfer the most important (or not😄) models to my project and use them there, or do not use my project for now until I do what you ask. My apologies😔
